Replace x11 CDT deps with xorg-libx11 and clarify GL deps
conda-forge/epoxy-feedstock pull request #8
Opened 2021-04-21 14:53 UTC by ryanvolz

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2021-04-21 15:36 UTC, ryanvolz commented
Certainly up for discussion, but I think experience has shown us that it is more hassle than it's worth using the CDTs instead of the conda-forge xorg packages. I have PRs prepared up the stack through `gtk3`.

2021-04-22 14:13 UTC, tschoonj requested changes

2021-04-22 14:13 UTC, tschoonj commented on recipe/meta.yaml
>      - meson !=0.56.*  # [win]
Since meson is now at 0.57.2, it is probably safe to remove the constraint for windows.

2021-04-22 14:25 UTC, tschoonj approved these changes
LGTM

2021-04-22 14:48 UTC, merged